# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["*"]
    paths:
      - "Backend/**"
  pull_request:
    branches: ["*"]
    paths:
      - "Backend/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: Backend/package-lock.json

      # Installera nödvändigheter
      - name: Install dependencies
        working-directory: ./Backend
        run:
          npm ci
      # 2. Formattera
      - name: Run Prettier
        run: npm run format --if-present
        working-directory: ./Backend
      # 3. Linta
      - name: Run ESLint
        working-directory: ./Backend
        run: |
          npm run lint
          npm run lint:fix
      # 4. Bygga
      - run: npm run build --if-present
        working-directory: ./Backend
      # 5. Testa lite
      - run: npm test
        working-directory: ./Backend